### ISSUE TITLE
Whole document reloading when using checkbox result in if statement

### ISSUE THREAD

**Issue by skropf** [conradbez/hyperstream#8]
I tried the interactive examples listed in the readme and tried around a bit.

The goal of the following snippet is to have the "Welcome ..." text only shown when the checkbox is checked. Unfortunately as soon as the checkbox is ticked the whole document/website gets reloaded and all variables are lost.

```python3
from hstream import hs

visitor_name = hs.text_input('Name')
checkbox = hs.checkbox('Would you like to be my friend?')

if checkbox: hs.markdown(f"Welcome {visitor_name}")
```

As I am not very deep into hstream and didn't find any documentation I wanted to point this behaviour out. If I just used it wrong I would appreciate it to be corrected!

BR

**Comment by conradbez** [comment]
Hi, yes this was a known limitation which I believe is now fixed in PR #7 

Please see if it's working with `hstream==0.0.15`

**Comment by conradbez** [comment]
the example demonstrates this behaviour now:
https://hstream-demo.fly.dev

**Comment by skropf** [comment]
Very cool, thanks a lot!
